version: '3.8'

services:
  factory-service:
    build: ./factory-service
    container_name: factory-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER=http://discovery-server:8761/eureka
    networks:
      - spring-net
    depends_on:
      - discovery-server

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER=http://discovery-server:8761/eureka
    networks:
      - spring-net
    depends_on:
      - discovery-server

  store-service:
    build: ./store-service
    container_name: store-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_SERVER=http://discovery-server:8761/eureka
    networks:
      - spring-net
    depends_on:
      - discovery-server

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge